name: Deploy Beta

env:
  package_prefix: maze-test

on:
  push:
    branches:
      - main

jobs:
  exports:
    name: Deploy to GH Pages
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Set git-semver version
        run: echo "version=$(npx @robpc/git-semver@0.1.6 ${REPO} ${REF})" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          REF: ${{ github.sha }}
      - name: Add Build Info
        uses: robpc/godot-build-info-action@v1
        with:
          version: ${{ env.version }}
      - name: Export html from Godot
        uses: robpc/godot-export-action@v4.0.2
        with:
          preset: web
          export_path: build/html/index.html
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: build/html